DATA_FIELDS  =  [
                ('Alternate URL', 'URL', 'Single', '/nitf/head/meta[@name="alternate_url"]/@content'),
                ('Article Abstract', 'String', 'Single', '/nitf/body/body.head/abstract'),
                ('Author Biography', 'String', 'Single', '/nitf/body/body.content/block[@class="author_info"]'),
                ('Banner', 'String', 'Single', '/nitf/head/meta[@name="banner"]/@content'),
                ('Biographical Categories', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="indexing_service" and @type="biographical_categories"]'),
                ('Body', 'String', 'Single', '/nitf/body/body.content/block[@class="full_text"]'),
                ('Byline', 'String', 'Single', '/nitf/body/body.head/byline[@class="print_byline"]'),
                ('Column Name', 'String', 'Single', '/nitf/head/meta[@name="column_name"]/@content'),
                ('Column Number', 'Integer', 'Single', '/nitf/head/meta[@name="print_column"]/@content'),
                ('Correction Date', 'Date', 'Single', '/nitf/head/meta[@name="correction_date"]/@content'),
                ('Correction Text', 'String', 'Single', '/nitf/body/body.content/block[@class="correction_text"]'),
                ('Credit', 'String', 'Single', '/nitf/head/docdata/doc.copyright/@holder'),
                ('Dateline', 'String', 'Single', '/nitf/body/body.head/dateline'),
                ('Day Of Week', 'String', 'Single', '/nitf/head/meta[@name="publication_day_of_week"]/@content'),
                ('Descriptors', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="indexing_service" and @type="descriptor"]'),
                ('Feature Page', 'String', 'Single', '/nitf/head/meta[@name="feature_page"]/@content'),
                ('General Online Descriptors', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="general_descriptor"]'),
                ('Guid', 'Long', 'Single', '/nitf/head/docdata/doc-id/@id-string'),
                ('Headline', 'String', 'Single', '/nitf/body[1]/body.head/hedline/hl1'),
                ('Kicker', 'String', 'Single', '/nitf/head/docdata/series/@series.name'),
                ('Lead Paragraph', 'String', 'Single', '/nitf/body/body.content/block[@class="lead_paragraph"]'),
                ('Locations', 'String', 'Multiple', '/nitf/head/docdata/identified-content/location[@class="indexing_service"]'),
                ('Names', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="indexing_service" and @type="names"]'),
                ('News Desk', 'String', 'Single', '/nitf/head/meta[@name="dsk"]/@content'),
                ('Normalized Byline', 'String', 'Single', '/nitf/body/body.head/byline[@class="normalized_byline"]'),
                ('Online Descriptors', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="descriptor"]'),
                ('Online Headline', 'String', 'Single', '/nitf/body[1]/body.head/hedline/hl2'),
                ('Online Lead Paragraph', 'String', 'Single', '/nitf/body/body.content/block[@class="online_lead_paragraph"]'),
                ('Online Locations', 'String', 'Multiple', '/nitf/head/docdata/identified-content/location[@class="online_producer"]'),
                ('Online Organizations', 'String', 'Multiple', '/nitf/head/docdata/identified-content/org[@class="online_producer"]'),
                ('Online People', 'String', 'Multiple', '/nitf/head/docdata/identified-content/person[@class="online_producer"]'),
                ('Online Section', 'String', 'Single', '/nitf/head/meta[@name="online_sections"]/@content'),
                ('Online Titles', 'String', 'Multiple', '/nitf/head/docdata/identified-content/object.title[@class="online_producer"]'),
                ('Organizations', 'String', 'Multiple', '/nitf/head/docdata/identified-content/org[@class="indexing_service"]'),
                ('Page', 'Integer', 'Single', '/nitf/head/meta[@name="print_page_number"]/@content'),
                ('People', 'String', 'Multiple', '/nitf/head/docdata/identified-content/person[@class="indexing_service"]'),
                ('Publication Date', 'Date', 'Single', '/nitf/head/pubdata/@date.publication'),
                ('Publication Day Of Month', 'Integer', 'Single', '/nitf/head/meta[@name="publication_day_of_month"]/@content'),
                ('Publication Month', 'Integer', 'Single', '/nitf/head/meta[@name="publication_month"]/@content'),
                ('Publication Year', 'Integer', 'Single', '/nitf/head/meta[@name="publication_year"]/@content'),
                ('Section', 'String', 'Single', '/nitf/head/meta[@name="print_section"]/@content'),
                ('Series Name', 'String', 'Single', '/nitf/head/meta[@name="series_name"]/@content'),
                ('Slug', 'String', 'Single', '/nitf/head/meta[@name="slug"]/@content'),
                ('Taxonomic Classifiers', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="taxonomic_classifier"]'),
                ('Titles', 'String', 'Multiple', '/nitf/head/docdata/identified-content/object.title[@class="indexing_service"]'),
                ('Types Of Material', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="types_of_material"]'),
                ('Url', 'URL', 'Single', '/nitf/head/pubdata/@ex-ref'),
                ('Word Count', 'Integer', 'Single', '/nitf/head/pubdata/@item-length'),
                ]

DATA_FIELDS_DICT = {title: xpath for title, _, _, xpath in DATA_FIELDS}
