# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='seed_query',
            field=models.CharField(default='seed', editable=False, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
