# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='display_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
