# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_topic_display_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
