# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20170504_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='seed_query',
            field=models.CharField(max_length=512),
        ),
    ]
