# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20170504_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
