# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_topic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
