# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0005_auto_20170518_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('confidence', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('mood', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('experience', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('difficulty', models.CharField(choices=[(1, 'Not at all'), (2, 'Slightly'), (3, 'Somewhat'), (4, 'Moderately'), (5, 'Extremely')], max_length=3)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='narrative',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretask',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
        migrations.AddField(
            model_name='pretask',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttask',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
        migrations.AddField(
            model_name='posttask',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
