# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0006_auto_20170620_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='posttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pretask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='posttask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.PostTask'),
        ),
        migrations.AddField(
            model_name='task',
            name='pretask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.PreTask'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
