# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_auto_20170620_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttask',
            name='confidence',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='experience',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='mood',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='familiarity',
            field=models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=3),
        ),
    ]
