# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20170620_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='username',
        ),
    ]
