# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0010_remove_topic_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_spent',
            new_name='timespent',
        ),
    ]
