# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_current_task'),
        ('topic', '0011_auto_20170621_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttask',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pretask',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='pretask',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='posttask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pretask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.DeleteModel(
            name='PostTask',
        ),
        migrations.DeleteModel(
            name='PreTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
