# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0012_auto_20170622_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('confidence', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('mood', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('experience', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('difficulty', models.CharField(choices=[('---', '---'), ('NOT AT ALL', 'Not at all'), ('SLIGHTLY', 'Slightly'), ('SOMEWHAT', 'Somewhat'), ('MODERATELY', 'Moderately'), ('EXTREMELY', 'Extremely')], default='---', max_length=35)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespent', models.DurationField(default=datetime.timedelta)),
                ('posttask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.PostTask')),
                ('pretask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.PreTask')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
