# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('', ''), ('MALE', 'Male'), ('FEMALE', 'Female')], max_length=56)),
                ('student_degree', models.CharField(choices=[('', ''), ('UNDERGRAD', 'An undergraduate student'), ('GRAD', 'A graduate student'), ('OTHER', 'Other. Please specify')], max_length=56)),
                ('student_degree_other', models.CharField(blank=True, max_length=128, null=True)),
                ('student_major', models.CharField(choices=[('', ''), ('ART', 'An art student'), ('STEM', 'A science, technology, engineering, or math student.'), ('OTHER', 'Other. Please specify')], max_length=56)),
                ('student_major_other', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(choices=[('', ''), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCE', 'Advance'), ('FLUENT', 'Fluent'), ('PROFICIENT', 'Proficient'), ('NATIVE', 'Native')], max_length=56)),
                ('search_engine_usage', models.CharField(choices=[('', ''), ('SEVERAL', 'Several times a day'), ('ONCE', 'At least once a day'), ('WEEK', 'At least once a week'), ('MONTH', 'At least once a month'), ('RARELY', 'Rarely (Less than one search a month on average)')], max_length=56)),
                ('expertise', models.CharField(choices=[('', ''), ('STRONG_DISAGREE', 'Strongly Disagree'), ('DISAGREE', 'Disagree'), ('NEUTRAL', 'Neutral'), ('AGREE', 'Agree'), ('STRONGLY_AGREE', 'Strongly Agree')], max_length=56)),
                ('trouble', models.CharField(choices=[('', ''), ('STRONG_DISAGREE', 'Strongly Disagree'), ('DISAGREE', 'Disagree'), ('NEUTRAL', 'Neutral'), ('AGREE', 'Agree'), ('STRONGLY_AGREE', 'Strongly Agree')], max_length=56)),
                ('help', models.CharField(choices=[('', ''), ('STRONG_DISAGREE', 'Strongly Disagree'), ('DISAGREE', 'Disagree'), ('NEUTRAL', 'Neutral'), ('AGREE', 'Agree'), ('STRONGLY_AGREE', 'Strongly Agree')], max_length=56)),
                ('enjoyment', models.CharField(choices=[('', ''), ('STRONG_DISAGREE', 'Strongly Disagree'), ('DISAGREE', 'Disagree'), ('NEUTRAL', 'Neutral'), ('AGREE', 'Agree'), ('STRONGLY_AGREE', 'Strongly Agree')], max_length=56)),
                ('training', models.CharField(choices=[('', ''), ('YES', 'Yes'), ('NO', 'No')], max_length=56)),
                ('training_feedback', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
