# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20170622_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posttask_task', to='progress.Task'),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pretask_task', to='progress.Task'),
        ),
    ]
