# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20170622_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
