# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0003_remove_tasksetting_show_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('---', '---'), ('1', 'Search Interface & Paragraph with Toggle Document Interface Together'), ('2', 'Paragraph with Toggle Document Interface Only'), ('3', 'Search Interface & Paragraph Interface Together'), ('4', 'Paragraph Interface Only'), ('5', 'Document Interface Only')], default='---', max_length=35)),
                ('helpful', models.CharField(choices=[('---', '---'), ('1', 'Keywords search and highlighting'), ('2', 'View full document'), ('3', 'Search interface'), ('4', 'Paragraph interface')], default='---', max_length=35)),
                ('familiar_before', models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not Familiar'), ('Somehow_Not', 'Somehow Not Familiar'), ('Neither_Nor_Not', 'Neither Familiar Nor Not Familiar'), ('Somewhat', 'Somewhat Familiar'), ('Very', 'Very Familiar')], default='---', max_length=35)),
                ('familiar_after', models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not Familiar'), ('Somehow_Not', 'Somehow Not Familiar'), ('Neither_Nor_Not', 'Neither Familiar Nor Not Familiar'), ('Somewhat', 'Somewhat Familiar'), ('Very', 'Very Familiar')], default='---', max_length=35)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_task', to='progress.Task')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='mood',
        ),
        migrations.AddField(
            model_name='posttask',
            name='close',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='posttask',
            name='complete',
            field=models.CharField(choices=[('---', '0'), ('Very_Not', '1-49'), ('Somehow_Not', '50-99'), ('Neither_Nor_Not', '100-499'), ('Somewhat', '500-999'), ('Very', '1,000 or more')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='posttask',
            name='helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='familiarity',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
    ]
