# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20170708_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timespent',
        ),
        migrations.AddField(
            model_name='task',
            name='active_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='last_activity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
