# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_auto_20170712_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='active_time',
            new_name='timespent',
        ),
    ]
