# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_auto_20170720_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exittask',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='helpful',
        ),
        migrations.AddField(
            model_name='exittask',
            name='doc_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='full_doc_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='keyword_search_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='keyword_shortcut_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='quote_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='recent_doc_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AddField(
            model_name='exittask',
            name='topic_helpful',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Useless'), ('Somehow_Not', 'Somehow Useless'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Useful'), ('Very', 'Very Useful')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='exittask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('1', 'Search Interface & Learning Interface show Paragraph with Toggle Document'), ('2', 'Learing Interface show Paragraphwith Toggle Document'), ('3', 'Search Interface &  Learning Interface show Paragraph'), ('4', 'Learning Interface show Paragraph'), ('5', 'Document Interative Interface Only')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='close',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Far(still lots of relevant documents to be found)'), ('Somehow_Not', 'Somehow Far'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Close'), ('Very', 'Very Close(found almost all relevant)')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Easy'), ('Somehow_Not', 'Somehow Easy'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Hard'), ('Very', 'Very Hard')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='familiarity',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Unfamiliar'), ('Somehow_Not', 'Somehow Unfamiliar'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Familiar'), ('Very', 'Very Familiar')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Easy'), ('Somehow_Not', 'Somehow Easy'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Hard'), ('Very', 'Very Hard')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='pretask',
            name='familiarity',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Unfamiliar'), ('Somehow_Not', 'Somehow Unfamiliar'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Familiar'), ('Very', 'Very Familiar')], default='---', max_length=35),
        ),
    ]
