# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_auto_20170720_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exittask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('1', 'Search Interface & Learning Interface showing Paragraph with Toggle Document'), ('2', 'Learing Interface showing Paragraph with Toggle Document'), ('3', 'Search Interface &  Learning Interface showing Paragraph'), ('4', 'Learning Interface showing Paragraph'), ('5', 'Document Interative Interface Only')], default='---', max_length=35),
        ),
        migrations.AlterField(
            model_name='posttask',
            name='close',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Far (still lots of relevant documents to be found)'), ('Somehow_Not', 'Somehow Far'), ('Neither_Nor_Not', 'Neutral'), ('Somewhat', 'Somewhat Close'), ('Very', 'Very Close (found almost all relevant)')], default='---', max_length=35),
        ),
    ]
