# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0003_auto_20170622_2007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=512)),
                ('doc_title', models.CharField(max_length=512)),
                ('doc_CAL_snippet', models.TextField()),
                ('doc_search_snippet', models.TextField()),
                ('query', models.CharField(blank=True, max_length=512, null=True)),
                ('relevant', models.BooleanField()),
                ('nonrelevant', models.BooleanField()),
                ('ontopic', models.BooleanField()),
                ('time_to_judge', models.CharField(blank=True, max_length=512, null=True)),
                ('isFromCAL', models.BooleanField()),
                ('isFromSearch', models.BooleanField()),
                ('isFromSearchModal', models.BooleanField()),
                ('fromMouse', models.BooleanField()),
                ('fromKeyboard', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together=set([('user', 'doc_id', 'task')]),
        ),
        migrations.AlterIndexTogether(
            name='judgement',
            index_together=set([('user', 'doc_id', 'task')]),
        ),
    ]
