# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='isKeyboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgement',
            name='isMouse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
