# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0002_auto_20170629_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='timeActive',
            new_name='timeVerbose',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='timeAway',
        ),
    ]
