# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0002_auto_20170508_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='isKeyboard',
            new_name='fromKeyboard',
        ),
        migrations.RenameField(
            model_name='judgement',
            old_name='isMouse',
            new_name='fromMouse',
        ),
    ]
