# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0003_auto_20170630_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='time_to_judge',
        ),
    ]
