# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20170504_1710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judgment', '0003_auto_20170508_1935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together=set([('user', 'doc_id', 'topic')]),
        ),
    ]
