# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0005_auto_20170513_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='notsure',
            new_name='ontopic',
        ),
    ]
