# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0006_judgement_isfromiterative'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='ctrl_f_terms_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_full_doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_title',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='judgement',
            name='search_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
