# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0006_auto_20170517_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='doc_title',
            field=models.CharField(default='NA', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgement',
            name='isFromSearch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgement',
            name='isFromSearchModal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
