# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0007_auto_20170518_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='doc_CAL_snippet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgement',
            name='doc_search_snippet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
