# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 22:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0008_auto_20170714_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_full_doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='found_ctrl_f_terms_in_title',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='timeVerbose',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='History'),
        ),
    ]
