# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0009_auto_20170715_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='doc_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
