# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAL', '0002_auto_20170503_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='topic_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
