# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('CAL', '0003_judgement_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='judgement',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
            preserve_default=False,
        ),
    ]
