# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAL', '0004_auto_20170503_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='time_to_judge',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
