# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAL', '0005_judgement_time_to_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='session',
        ),
        migrations.AddField(
            model_name='judgement',
            name='isFromCAL',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgement',
            name='query',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
