# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_treatment_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='treatment_num',
            new_name='treatment',
        ),
    ]
