# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
    ]
