# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 19:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
