# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170702_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_task_active_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
