# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170712_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='user',
            name='cur_task_last_activity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
