# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170712_0034_squashed_0009_auto_20170712_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='treatment',
        ),
    ]
