# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170620_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_task',
        ),
    ]
