# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('users', '0007_remove_user_current_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Task'),
        ),
    ]
