# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170712_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cur_task_active_time',
        ),
        migrations.AddField(
            model_name='user',
            name='_cur_task_active_time',
            field=models.FloatField(default=0.0),
        ),
    ]
