# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170712_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_cur_task_active_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cur_task_last_activity',
        ),
    ]
