# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 16:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=512)),
                ('doc_title', models.CharField(max_length=512)),
                ('doc_CAL_snippet', models.TextField()),
                ('doc_search_snippet', models.TextField()),
                ('query', models.CharField(blank=True, max_length=512, null=True)),
                ('relevant', models.BooleanField()),
                ('nonrelevant', models.BooleanField()),
                ('ontopic', models.BooleanField()),
                ('isFromCAL', models.BooleanField()),
                ('isFromSearch', models.BooleanField()),
                ('isFromSearchModal', models.BooleanField()),
                ('fromMouse', models.BooleanField()),
                ('fromKeyboard', models.BooleanField()),
                ('timeVerbose', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True, verbose_name='History')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
