# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-27 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgment', '0002_judgement_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together=set([('user', 'doc_id', 'task')]),
        ),
        migrations.AlterIndexTogether(
            name='judgement',
            index_together=set([('user', 'doc_id', 'task')]),
        ),
    ]
