# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0003_auto_20180726_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
