# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-20 22:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0006_auto_20180804_1908'),
        ('judgment', '0003_auto_20180726_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=512)),
                ('rel', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=24, null=True)),
                ('time_verbose', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='History')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='judgement',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='judgement',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='task',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Judgement',
        ),
        migrations.AlterUniqueTogether(
            name='judgment',
            unique_together=set([('user', 'doc_id', 'task')]),
        ),
        migrations.AlterIndexTogether(
            name='judgment',
            index_together=set([('user', 'doc_id', 'task')]),
        ),
    ]
