# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0003_auto_20170702_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='fromKeyboard',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='fromMouse',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='isFromCAL',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='isFromSearch',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='isFromSearchModal',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='nonrelevant',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='ontopic',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='relevant',
            field=models.NullBooleanField(),
        ),
    ]
