# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_auto_20170703_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='ontopic',
        ),
        migrations.AddField(
            model_name='judgement',
            name='highlyRelevant',
            field=models.NullBooleanField(),
        ),
    ]
