# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-31 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_judgement_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='isFromCAL',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='isFromIterative',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='isFromSearch',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='isFromSearchModal',
        ),
    ]
