# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-06-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0005_auto_20200531_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='fromKeyboard',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='fromMouse',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='highlyRelevant',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='nonrelevant',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='relevant',
        ),
        migrations.AddField(
            model_name='judgement',
            name='method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='judgement',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
