# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0005_auto_20170704_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='isFromIterative',
            field=models.NullBooleanField(),
        ),
    ]
