# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-06-01 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0006_auto_20200531_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Judgement',
            new_name='Judgment',
        ),
    ]
