# Generated by Django 3.0.5 on 2020-06-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200604_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_task',
            new_name='current_session',
        ),
    ]
