# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 17:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170702_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sequence',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
