# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('users', '0006_auto_20170712_0034'), ('users', '0007_auto_20170712_0041'), ('users', '0008_auto_20170712_0046'), ('users', '0009_auto_20170712_1927')]

    dependencies = [
        ('users', '0005_auto_20170702_1746'),
    ]

    operations = [
    ]
