# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20180723_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_number_of_judgments',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
