# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-26 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_task_max_number_of_judgments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='strategy',
            field=models.CharField(choices=[('para', 'Paragraph (CAL)'), ('para_scal', 'Paragraph (SCAL)')], default='para', max_length=64),
            preserve_default=False,
        ),
    ]
