# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20170707_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exittask',
            name='helpful',
            field=models.CharField(choices=[('---', '---'), ('1', 'Keywords Search and Highlighting'), ('2', 'View Full Document'), ('3', 'Search Interface'), ('4', 'Paragraph Interface')], default='---', max_length=35),
        ),
    ]
