# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20170707_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exittask',
            name='familiar_after',
        ),
        migrations.RemoveField(
            model_name='exittask',
            name='familiar_before',
        ),
        migrations.AddField(
            model_name='posttask',
            name='familiarity',
            field=models.CharField(choices=[('---', '---'), ('Very_Not', 'Very Not'), ('Somehow_Not', 'Somehow Not'), ('Neither_Nor_Not', 'Neither Nor Not'), ('Somewhat', 'Somewhat'), ('Very', 'Very')], default='---', max_length=35),
        ),
    ]
