# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_auto_20180804_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='strategy',
            field=models.CharField(choices=[('doc', 'Document (CAL)'), ('para', 'Paragraph (CAL)'), ('doc_scal', 'Document (S-CAL)'), ('para_scal', 'Paragraph (S-CAL)')], max_length=64),
        ),
    ]
