# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_auto_20170712_1924_squashed_0008_auto_20170712_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exittask',
            name='task',
        ),
    ]
