# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_auto_20170720_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('MALE', 'Male'), ('FEMALE', 'Female'), ('TERM', 'I prefer another term'), ('NA', 'I prefer not to say')], max_length=56, null=True),
        ),
    ]
