# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_auto_20170721_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exittask',
            name='difficulty',
            field=models.CharField(choices=[('---', '---'), ('1', 'Search Interface & Learning Interface showing Paragraph with Toggle Document'), ('2', 'Learing Interface showing Paragraph with Toggle Document'), ('3', 'Search Interface &  Learning Interface showing Paragraph'), ('4', 'Learning Interface showing Paragraph'), ('5', 'Document Iterative Interface Only')], default='---', max_length=35),
        ),
    ]
