# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0016_auto_20170731_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic',
            name='username',
        ),
        migrations.RemoveField(
            model_name='exittask',
            name='username',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='posttask',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pretask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='pretask',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='posttask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pretask',
        ),
        migrations.DeleteModel(
            name='Demographic',
        ),
        migrations.DeleteModel(
            name='ExitTask',
        ),
        migrations.DeleteModel(
            name='PostTask',
        ),
        migrations.DeleteModel(
            name='PreTask',
        ),
    ]
