# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_auto_20171027_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='progress.TaskSetting'),
        ),
    ]
